local lcpp = require("lcpp")

local glue = [[
#define __TINYC__
#define static
#define __thread
typedef struct FILE FILE;
typedef long int ptrdiff_t;
typedef long unsigned int size_t;
]]

function trim_multilines(str)
    local lines = str:gmatch("([^\r\n]+)\r?\n?")
    local output = lines()
    for line in lines do
        output = output .. "\n" .. line
    end
    return output
end

io.input("./fwk.h")
local fwk_h = io.read("*all")
fwk_h = fwk_h:gsub("#line", "//#line")
fwk_h = fwk_h:gsub("#include", "//#include")

print('--autogenerated luajit bindings. do not edit. ' .. os.date("%Y/%m/%d"))
print('local ffi = require("ffi")')
print('ffi.cdef([[')

local result = lcpp.compile(glue .. fwk_h)
print( trim_multilines(result) )

print(']])')
print('return ffi.load("fwk")')
